### ISSUE TITLE
Settings file for other Dynamic Learning methods such as NN

### ISSUE THREAD

**Issue by nikhilpodila** [rr-learning/transferable_dynamics_dataset#1]
I see that it is not very clear on how I can run NN or other methods from this code, since the Settings file doesn't exist in this repo. From the code, I was able to decode a few JSON parameters but still wasn't very clear. I tried looking at previous commits, but the Settings folder wasn't there either.

After a bit of searching, I found the Settings folder in [this link in Gitlab](https://gitlab.tue.mpg.de/dagudelo/dynamics_learning_code/-/tree/master/Settings). Can you include the Settings folder in this repo as well, so it maybe complete for future references, in case the Gitlab link is deleted? Thanks.
Or do you suggest that the Gitlab repo is a more complete overview of this project?

**Comment by DiegoAE** [comment]
Thanks for your feeback @nikhilpodila . We have just added some settings examples in a directory.
Regarding which repository to use, we'll try to keep this one (GitHub) up to date. The Gitlab repo will be eventually deprecated.
I'm closing this issue for now but feel free to re-open it if there are still issues.
